const state={profile:{name:'مهمان',avatar:'https://i.pravatar.cc/150?img=23'},connected:null,wizardStep:0,wizard:{plan:null,user:{},addons:[],accepted:false},flags:{mic:true,deafen:false,afk:false,sound:true},public:[{n:'Tehran Prime',o:88},{n:'Esports Arena',o:57},{n:'Dev Community',o:33}],my:[{n:'My Clan',s:64},{n:'Office HQ',s:32}],tree:[{c:'Lobby',u:[['Ali',1],['Reza',0]]},{c:'Gaming',u:[['Sara',1],['Nima',0]]},{c:'AFK',u:[['Bot',0]]}]};
const titles=['معرفی','پلن','مشخصات','افزودنی','قرارداد','پرداخت','تحویل'];const plans=[['starter',32,'690,000'],['pro',64,'1,290,000'],['ultra',128,'2,490,000']];
const $=x=>document.getElementById(x);const toast=m=>{const d=document.createElement('div');d.className='toast';d.textContent=m;$('toastContainer').appendChild(d);setTimeout(()=>d.remove(),2600)};
function renderDash(){ $('topName').textContent=state.profile.name;$('topAvatar').src=state.profile.avatar;const q=$('serverSearch').value?.toLowerCase()||'';$('publicServers').innerHTML=state.public.filter(s=>s.n.toLowerCase().includes(q)).map(s=>`<div class='item'><div><b>${s.n}</b><small>${s.o} online</small></div><button class='btn' onclick='joinServer("${s.n}")'>Join</button></div>`).join('');$('myServers').innerHTML=state.my.map(s=>`<div class='item'><div><b>${s.n}</b><small>${s.s} slot</small></div><button class='btn' onclick='joinServer("${s.n}")'>ورود</button></div>`).join('')}
function show(v){['dashboardView','serverView'].forEach(id=>$(id).classList.remove('active'));$(v).classList.add('active')}
function renderServer(){ $('serverTitle').textContent=`${state.connected} | IranVoice`;$('channelTree').innerHTML=state.tree.map((x,i)=>`<div class='channel ${i===0?'active':''}' onclick='openChannel(${i})'>📁 ${x.c}</div>${x.u.map(u=>`<div class='sub'>${u[1]?'🟢':'⚪'} ${u[0]}</div>`).join('')}`).join('');openChannel(0,false)}
function openChannel(i,toasty=true){const ch=state.tree[i];$('activeChannelName').textContent=`# ${ch.c}`;$('channelMembers').innerHTML=ch.u.map(u=>`<div class='member ${u[1]?'':'muted'}'><span class='dot ${u[1]?'speak':''}'></span>${u[0]}</div>`).join('');if(toasty)toast(`ورود به ${ch.c}`)} window.openChannel=openChannel;
function joinServer(name){$('joinModal').classList.remove('hidden');const st=['بررسی وضعیت سرور','ایجاد سشن کاربر','دریافت لیست چنل‌ها','اتصال صوتی','ورود موفق'];let i=0;const go=()=>{$('progressBar').style.width=((i+1)/st.length*100)+'%';$('connectSteps').innerHTML=st.map((s,x)=>`<div>${x<i?'✅':x===i?'🔄':'⏳'} ${s}</div>`).join('');if(i<st.length-1){i++;setTimeout(go,500)}else setTimeout(()=>{$('joinModal').classList.add('hidden');state.connected=name;renderServer();show('serverView');toast('با موفقیت وارد شدید')},450)};go()} window.joinServer=joinServer;
function closeModal(id){$(id).classList.add('hidden')} window.closeModal=closeModal;
function renderWizard(){ $('wizardSteps').innerHTML=titles.map((t,i)=>`<div class='wstep ${i===state.wizardStep?'a':''}'>${t}</div>`).join('');let h='';if(state.wizardStep===0)h='<p>ساخت سریع سرور اختصاصی</p>';if(state.wizardStep===1)h=plans.map(p=>`<div class='plan ${state.wizard.plan===p[0]?'sel':''}' onclick='pickPlan("${p[0]}")'><b>${p[0]}</b><span>${p[1]} Slot - ${p[2]}</span></div>`).join('');if(state.wizardStep===2)h=`<input id='wName' placeholder='نام' value='${state.wizard.user.name||''}'><input id='wPhone' placeholder='شماره' value='${state.wizard.user.phone||''}'>`;if(state.wizardStep===3)h=`<div class='item' onclick='toggleAddon("music")'>Music Bot ${state.wizard.addons.includes('music')?'✅':''}</div>`;if(state.wizardStep===4)h=`<label><input type='checkbox' ${state.wizard.accepted?'checked':''} onchange='acc(this.checked)'> تایید قوانین</label>`;if(state.wizardStep===5)h=`<div class='item'><b>زرین پال</b><span>پرداخت امن</span></div>`;if(state.wizardStep===6)h='<h4>✅ سرور ساخته شد</h4>';$('wizardBody').innerHTML=h;validate();$('nextStep').textContent=state.wizardStep===6?'پایان':'ادامه'}
function validate(){let ok=true;const s=state.wizardStep;if(s===1)ok=!!state.wizard.plan;if(s===2){state.wizard.user={name:$('wName')?.value||'',phone:$('wPhone')?.value||''};ok=Boolean(state.wizard.user.name&&state.wizard.user.phone)}if(s===4)ok=state.wizard.accepted;$('nextStep').disabled=!ok}
function pickPlan(x){state.wizard.plan=x;renderWizard()} window.pickPlan=pickPlan;function toggleAddon(x){state.wizard.addons=state.wizard.addons.includes(x)?[]:[x];renderWizard()} window.toggleAddon=toggleAddon;function acc(v){state.wizard.accepted=v;validate()} window.acc=acc;
$('openWizard').onclick=()=>{$('wizardModal').classList.remove('hidden');state.wizardStep=0;renderWizard()};$('prevStep').onclick=()=>{if(state.wizardStep>0)state.wizardStep--;renderWizard()};$('nextStep').onclick=()=>{if(state.wizardStep===2)validate();if($('nextStep').disabled)return;if(state.wizardStep<6){state.wizardStep++;if(state.wizardStep===6){const p=plans.find(x=>x[0]===state.wizard.plan);state.my.unshift({n:`${p[0]} server`,s:p[1]});renderDash();toast('سرور خریداری شد')}renderWizard()}else closeModal('wizardModal')};
$('serverSearch').oninput=renderDash;$('joinByIp').onclick=()=>joinServer($('ipInput').value||'Custom IP');$('backDashboard').onclick=()=>show('dashboardView');
$('muteMic').onclick=e=>{state.flags.mic=!state.flags.mic;e.target.textContent=state.flags.mic?'🎤 Mute Mic':'🎤 Unmute Mic'};$('deafen').onclick=e=>{state.flags.deafen=!state.flags.deafen;e.target.textContent=state.flags.deafen?'🔈 Undeafen':'🔇 Deafen'};$('afkBtn').onclick=e=>{state.flags.afk=!state.flags.afk;e.target.textContent=state.flags.afk?'✅ Back from AFK':'🛌 AFK'};$('soundBtn').onclick=e=>{state.flags.sound=!state.flags.sound;e.target.textContent=state.flags.sound?'🔈 Sound On':'🔕 Sound Off'};
$('openProfile').onclick=()=>{$('profileModal').classList.remove('hidden');$('profileName').value=state.profile.name;$('profilePreview').src=state.profile.avatar};$('avatarUpload').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>$('profilePreview').src=r.result;r.readAsDataURL(f)};$('saveProfile').onclick=()=>{state.profile.name=$('profileName').value||'مهمان';state.profile.avatar=$('profilePreview').src;closeModal('profileModal');renderDash();toast('پروفایل بروزرسانی شد')};
renderDash();toast('خوش آمدید');
